node {
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }

        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }

        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
        }

        stage('Manual Approval') {
            input(message: "Lanjutkan ke tahap Deploy?")
        }

        stage('Deploy') { 
            sleep(time:60, unit: "SECONDS")
            sh './jenkins/scripts/deliver.sh'
        }
    }
}